### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by amackera**

### CODE REVIEW

**Comment by jameskeane** [comment]
something something reviewme

**Comment by jameskeane** [comment]
reviewme

**Comment by jameskeane** [comment]
reviewme

**Comment by jameskeane** [comment]
reviewme

**Comment by amackera** [comment]
claimzed

**Comment by jameskeane** [comment]
reviewme

**Comment by jameskeane** [comment]
reviewme

**Comment by jameskeane** [comment]
reviewme

**Comment by jameskeane** [comment]
reviewme

**Comment by jameskeane** [comment]
reviewme

**Pull request closed without merging**
